### ISSUE TITLE
CODE_OF_CONDUCT is out of date

### ISSUE THREAD

**Issue by hzierer** [eclipse-tractusx/vas-country-risk-backend#15]
found during QG4 Check #14 

the current one can be found here: https://raw.githubusercontent.com/eclipse/.github/master/CODE_OF_CONDUCT.md

**Comment by fabiodmota** [comment]
done https://github.com/eclipse-tractusx/vas-country-risk-backend/commit/3e1c4107f77dd753bde17cbaabb43864902a06f9#diff-ffdbe3a1e7ee93cacfc080b6c635ccf3a8f6b0f00f2fb884f78c6b5f9dac8fd2
