### ISSUE TITLE
Question: Is there a specific purpose for moving the `helm-charts` of the `vas-country-risk-backend` to the country risk frontend repository?

### ISSUE THREAD

**Issue by ChauhanKrunal** [eclipse-tractusx/vas-country-risk-backend#19]
While reading the release notes for `v1.1.1`, I discovered that the `helm-charts` for the `vas-country-risk-backend` have been migrated to `vas-country-risk` repository, which appears to be source code for the frontend. If we want a clear separation between the business logic of the code and the `CD` aspect of it, I guess moving the helm charts of the country risk backend and frontend to another repository that will only be used for continuous delivery. which seems a quite `gitops` approach and it would be more concise and easy to maintain.

If you guys already have this approach in your mind, so are you guys taking it in further release or country risk backend helm-charts will always stay in the country risk frontend repo?

**Comment by fabiodmota** [comment]
We removed the helm charts from the backend repository because we were required to have a leading repository with both apps in helm chart, meaning this lead will be our frontend named vas-country-risk. The backend will only contain source code in the language it is created along with the read me docs that will point to the other repo for a full deployment.

**Comment by ChauhanKrunal** [comment]
> We removed the helm charts from the backend repository because we were required to have a leading repository with both apps in helm chart, meaning this lead will be our frontend named vas-country-risk. The backend will only contain source code in the language it is created along with the read me docs that will point to the other repo for a full deployment.

@fabiodmota It makes sense to combine the helm charts for the frontend and backend in a single repository, but wouldn't it be ideal to move the helm charts for the entire country risk app stack to a different repository instead of include them in the frontend's source code? Because of how much more segregated that would be, we would only need to look at the deployment charts utilising a gitops method as opposed to navigating to the frontend's source code.

**Comment by fabiodmota** [comment]
@ChauhanKrunal Hi sorry for the late response and yes we are counting to move only charts to a repo maybe on future release but for now we are not allocating efforts to country risk , the current code and flow charts were the current guide at the time .

Thank you for pointing out
